import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialWorkSchema1777239129629 implements MigrationInterface {
    name = 'InitialWorkSchema1777239129629'
    async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "c0"."tags_type_enum" AS ENUM('genre', 'theme', 'demographic', 'format', 'content')`);
        await queryRunner.query(`CREATE TABLE "c0"."tags" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, "type" "c0"."tags_type_enum" NOT NULL DEFAULT 'genre', "color" character varying(7), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "usageCount" integer NOT NULL DEFAULT '0', "createdById" uuid, "updatedById" uuid, CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "UQ_b3aa10c29ea4e61a830362bd25a" UNIQUE ("slug"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d90243459a697eadb8ad56e909" ON "c0"."tags" ("name") `);
        await queryRunner.query(`CREATE TABLE "c0"."comments" ("id" uuid NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "isEdited" boolean NOT NULL DEFAULT false, "isPinned" boolean NOT NULL DEFAULT false, "isSpoiler" boolean NOT NULL DEFAULT false, "likeCount" integer NOT NULL DEFAULT '0', "dislikeCount" integer NOT NULL DEFAULT '0', "replyCount" integer NOT NULL DEFAULT '0', "workId" uuid, "chapterId" uuid, "userId" uuid NOT NULL, "parentCommentId" uuid, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "c0"."ratings" ("id" uuid NOT NULL, "score" numeric(3,2) NOT NULL, "review" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "workId" uuid NOT NULL, CONSTRAINT "PK_0f31425b073219379545ad68ed9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4d0b0e3a4c4af854d225154ba4" ON "c0"."ratings" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c85192d9b1abbd97d8962fd622" ON "c0"."ratings" ("workId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3e4b080bb7591bb8ec918a3c64" ON "c0"."ratings" ("userId", "workId") `);
        await queryRunner.query(`CREATE TABLE "c0"."collection_entries" ("id" uuid NOT NULL, "position" integer NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "collectionId" uuid NOT NULL, "workId" uuid NOT NULL, CONSTRAINT "PK_4ed9fd0633a4ae73ff070de3866" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de1a5a32f043041ab0e7048b14" ON "c0"."collection_entries" ("collectionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c196694a622fd7a594b6018b4" ON "c0"."collection_entries" ("workId") `);
        await queryRunner.query(`CREATE INDEX "IDX_616ce4cf6593257b481160f85d" ON "c0"."collection_entries" ("collectionId", "position") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fdc119b50c517c0e9955531100" ON "c0"."collection_entries" ("collectionId", "workId") `);
        await queryRunner.query(`CREATE TABLE "c0"."collections" ("id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "coverUrl" character varying(500), "isPublic" boolean NOT NULL DEFAULT true, "isFeatured" boolean NOT NULL DEFAULT false, "workCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdById" uuid, CONSTRAINT "PK_21c00b1ebbd41ba1354242c5c4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed225078e8bf65b448b69105b4" ON "c0"."collections" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_a14032a082010e4663568afd54" ON "c0"."collections" ("createdById") `);
        await queryRunner.query(`CREATE TYPE "c0"."user_sanctions_type_enum" AS ENUM('BAN', 'SUSPENSION')`);
        await queryRunner.query(`CREATE TYPE "c0"."user_sanctions_reason_enum" AS ENUM('HARASSMENT', 'SPAM', 'INAPPROPRIATE_CONTENT', 'IMPERSONATION', 'CHEATING', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "c0"."user_sanctions" ("id" uuid NOT NULL, "type" "c0"."user_sanctions_type_enum" NOT NULL, "reason" "c0"."user_sanctions_reason_enum" NOT NULL, "description" text, "expiresAt" TIMESTAMP WITH TIME ZONE, "revokedAt" TIMESTAMP WITH TIME ZONE, "revokedById" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "issuedById" uuid NOT NULL, CONSTRAINT "PK_85a2b44306f6533feff0cf74aca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_877f31988ad8db4e3c589a9e22" ON "c0"."user_sanctions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e3a2487f5b55206963e560f9f" ON "c0"."user_sanctions" ("issuedById") `);
        await queryRunner.query(`CREATE TYPE "c0"."users_role_enum" AS ENUM('USER', 'ADMIN', 'OWNER', 'MODERATOR')`);
        await queryRunner.query(`CREATE TYPE "c0"."users_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'BANNED', 'DELETED')`);
        await queryRunner.query(`CREATE TYPE "c0"."users_subscriptiontier_enum" AS ENUM('free', 'member', 'elite', 'platinum', 'diamond', 'legendary')`);
        await queryRunner.query(`CREATE TYPE "c0"."users_preferredlanguage_enum" AS ENUM('pt', 'en', 'es', 'ja', 'ko', 'zh', 'fr', 'de', 'it', 'ru')`);
        await queryRunner.query(`CREATE TABLE "c0"."users" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "userName" character varying(100) NOT NULL, "password" character varying(255) NOT NULL, "biography" text, "birthDate" date, "email" character varying(255) NOT NULL, "role" "c0"."users_role_enum" NOT NULL DEFAULT 'USER', "status" "c0"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "subscriptionTier" "c0"."users_subscriptiontier_enum" NOT NULL DEFAULT 'free', "isVerified" boolean NOT NULL DEFAULT false, "lastPasswordChange" TIMESTAMP WITH TIME ZONE, "emailVerifiedAt" TIMESTAMP WITH TIME ZONE, "verificationToken" character varying(255), "resetPasswordToken" character varying(255), "resetPasswordExpires" TIMESTAMP WITH TIME ZONE, "profilePictureUrl" character varying(500), "bannerUrl" character varying(500), "address" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "worksCreated" integer NOT NULL DEFAULT '0', "chaptersCreated" integer NOT NULL DEFAULT '0', "commentsCount" integer NOT NULL DEFAULT '0', "favoritesCount" integer NOT NULL DEFAULT '0', "ratingsCount" integer NOT NULL DEFAULT '0', "showMatureContent" boolean NOT NULL DEFAULT true, "preferredLanguage" "c0"."users_preferredlanguage_enum" NOT NULL DEFAULT 'en', "theme" character varying NOT NULL DEFAULT 'dark', CONSTRAINT "UQ_226bb9aa7aa8a69991209d58f59" UNIQUE ("userName"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "c0"."manga_details" ("workId" uuid NOT NULL, "chapterCount" integer, "volumeCount" integer, CONSTRAINT "PK_3252e63fe8ce649770e57f35e69" PRIMARY KEY ("workId"))`);
        await queryRunner.query(`CREATE TABLE "c0"."anime_details" ("workId" uuid NOT NULL, "episodeCount" integer, "durationMinutes" integer, "season" character varying(50), "seasonYear" integer, CONSTRAINT "PK_21ab4364b15e81e739b47f02c73" PRIMARY KEY ("workId"))`);
        await queryRunner.query(`CREATE TYPE "c0"."works_type_enum" AS ENUM('MANGA', 'MANHWA', 'MANHUA', 'NOVEL', 'ONE_SHOT', 'ANIME', 'OVA', 'MOVIE', 'SPECIAL')`);
        await queryRunner.query(`CREATE TYPE "c0"."works_visibilitystatus_enum" AS ENUM('PUBLISHED', 'UNLISTED', 'PRIVATE', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "c0"."works_publicationstatus_enum" AS ENUM('DRAFT', 'ONGOING', 'HIATUS', 'COMPLETED', 'DROPPED')`);
        await queryRunner.query(`CREATE TYPE "c0"."works_moderationstatus_enum" AS ENUM('OK', 'REPORTED', 'FLAGGED', 'RESTRICTED', 'DELETED')`);
        await queryRunner.query(`CREATE TABLE "c0"."works" ("id" uuid NOT NULL, "title" character varying(255) NOT NULL, "nativeTitle" character varying(255), "englishTitle" character varying(255), "alternativeTitles" jsonb, "description" text, "coverUrl" character varying(500) NOT NULL, "bannerUrl" character varying(500), "type" "c0"."works_type_enum" NOT NULL, "demographic" character varying(50), "contentRating" character varying(50), "visibilityStatus" "c0"."works_visibilitystatus_enum" NOT NULL DEFAULT 'PUBLISHED', "publicationStatus" "c0"."works_publicationstatus_enum" NOT NULL DEFAULT 'DRAFT', "moderationStatus" "c0"."works_moderationstatus_enum" NOT NULL DEFAULT 'OK', "startYear" integer, "endYear" integer, "averageRating" real NOT NULL DEFAULT '0', "ratingCount" integer NOT NULL DEFAULT '0', "ratingDistribution" jsonb, "bayesianScore" real NOT NULL DEFAULT '0', "favoriteCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', "planToReadCount" integer NOT NULL DEFAULT '0', "readingCount" integer NOT NULL DEFAULT '0', "completedCount" integer NOT NULL DEFAULT '0', "onHoldCount" integer NOT NULL DEFAULT '0', "droppedCount" integer NOT NULL DEFAULT '0', "popularityScore" real NOT NULL DEFAULT '0', "popularityRank" integer, "scoreRank" integer, "featuredWeight" integer NOT NULL DEFAULT '0', "slug" character varying(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdById" uuid, "updatedById" uuid, CONSTRAINT "UQ_770b186e9db00e82890afef0aa5" UNIQUE ("slug"), CONSTRAINT "PK_a9ffbf516ba6e52604b29e5cce0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4efbf189b941c4cd29e278f87d" ON "c0"."works" ("title") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_770b186e9db00e82890afef0aa" ON "c0"."works" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc7b60e91e76fae97b67a165a8" ON "c0"."works" ("popularityScore") `);
        await queryRunner.query(`CREATE INDEX "IDX_8273d23f58ae6e8b03e35a6d53" ON "c0"."works" ("bayesianScore") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f1e6c57e950277bedba0323d0" ON "c0"."works" ("startYear") `);
        await queryRunner.query(`CREATE INDEX "IDX_108358e19103e130c8f64405b1" ON "c0"."works" ("visibilityStatus", "moderationStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_e8cdc8010caab38b2c5f139639" ON "c0"."works" ("publicationStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d85186e28e27d51cce3aec295" ON "c0"."works" ("contentRating") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f26e97e48cf2da0c1390bf089" ON "c0"."works" ("demographic") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c7a194ef8142e025933a24e0a" ON "c0"."works" ("type") `);
        await queryRunner.query(`CREATE TABLE "c0"."cities" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "stateId" integer NOT NULL, "latitude" numeric, "longitude" numeric, CONSTRAINT "PK_4762ffb6e5d198cfec5606bc11e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a0ae8d83b7d32359578c486e7f" ON "c0"."cities" ("name") `);
        await queryRunner.query(`CREATE TABLE "c0"."states" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "countryId" integer NOT NULL, CONSTRAINT "PK_09ab30ca0975c02656483265f4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe52f02449eaf27be2b2cb7acd" ON "c0"."states" ("name") `);
        await queryRunner.query(`CREATE TABLE "c0"."countries" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "iso" character varying(3) NOT NULL, CONSTRAINT "UQ_a1c0d005a87cc318b4ddda4d925" UNIQUE ("iso"), CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fa1376321185575cf2226b1491" ON "c0"."countries" ("name") `);
        await queryRunner.query(`CREATE TABLE "c0"."timezones" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "abbreviation" character varying(10) NOT NULL, "gmtOffset" integer NOT NULL, "gmtOffsetName" character varying(20) NOT NULL, "tzName" character varying NOT NULL, "zoneName" character varying NOT NULL, "countryId" integer NOT NULL, CONSTRAINT "PK_589871db156cc7f92942334ab7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6248bf632ed7b73d6e96a2621" ON "c0"."timezones" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c7ec626ba5f8d4aa87ebb8d113" ON "c0"."timezones" ("zoneName", "countryId") `);
        await queryRunner.query(`CREATE TABLE "c0"."sessions" ("id" uuid NOT NULL, "userId" uuid NOT NULL, "refreshTokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_57de40bc620f456c7311aa3a1e" ON "c0"."sessions" ("userId") `);
        await queryRunner.query(`CREATE TABLE "c0"."work_tags" ("work_id" uuid NOT NULL, "tag_id" uuid NOT NULL, CONSTRAINT "PK_e2bdef324689c6f7a0f299a3c64" PRIMARY KEY ("work_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d9652285b640595c4e10185b2a" ON "c0"."work_tags" ("work_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_55598cd484850a747685c78723" ON "c0"."work_tags" ("tag_id") `);
        await queryRunner.query(`CREATE TABLE "c0"."comments_closure" ("id_ancestor" uuid NOT NULL, "id_descendant" uuid NOT NULL, CONSTRAINT "PK_a02e5093a5d47a64f1fd473d1ef" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89a2762362d968c2939b6fab19" ON "c0"."comments_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2164211fd6ab117cfb2ab8ba9" ON "c0"."comments_closure" ("id_descendant") `);
        await queryRunner.query(`ALTER TABLE "c0"."tags" ADD CONSTRAINT "FK_e56de5f3dcb3c112de1e983b8e7" FOREIGN KEY ("createdById") REFERENCES "c0"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."tags" ADD CONSTRAINT "FK_613bccbbe697ffcb6d454c8c137" FOREIGN KEY ("updatedById") REFERENCES "c0"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."comments" ADD CONSTRAINT "FK_0a9a028f859a61e9d1d961ec3ef" FOREIGN KEY ("workId") REFERENCES "c0"."works"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."comments" ADD CONSTRAINT "FK_7e8d7c49f218ebb14314fdb3749" FOREIGN KEY ("userId") REFERENCES "c0"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."comments" ADD CONSTRAINT "FK_4875672591221a61ace66f2d4f9" FOREIGN KEY ("parentCommentId") REFERENCES "c0"."comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."ratings" ADD CONSTRAINT "FK_4d0b0e3a4c4af854d225154ba40" FOREIGN KEY ("userId") REFERENCES "c0"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."ratings" ADD CONSTRAINT "FK_c85192d9b1abbd97d8962fd622b" FOREIGN KEY ("workId") REFERENCES "c0"."works"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."collection_entries" ADD CONSTRAINT "FK_de1a5a32f043041ab0e7048b143" FOREIGN KEY ("collectionId") REFERENCES "c0"."collections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."collection_entries" ADD CONSTRAINT "FK_3c196694a622fd7a594b6018b40" FOREIGN KEY ("workId") REFERENCES "c0"."works"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."collections" ADD CONSTRAINT "FK_a14032a082010e4663568afd54b" FOREIGN KEY ("createdById") REFERENCES "c0"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."user_sanctions" ADD CONSTRAINT "FK_78bea893daa1ed87b5ebcd3d39d" FOREIGN KEY ("revokedById") REFERENCES "c0"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."user_sanctions" ADD CONSTRAINT "FK_877f31988ad8db4e3c589a9e22e" FOREIGN KEY ("userId") REFERENCES "c0"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."user_sanctions" ADD CONSTRAINT "FK_0e3a2487f5b55206963e560f9f1" FOREIGN KEY ("issuedById") REFERENCES "c0"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."manga_details" ADD CONSTRAINT "FK_3252e63fe8ce649770e57f35e69" FOREIGN KEY ("workId") REFERENCES "c0"."works"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."anime_details" ADD CONSTRAINT "FK_21ab4364b15e81e739b47f02c73" FOREIGN KEY ("workId") REFERENCES "c0"."works"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."works" ADD CONSTRAINT "FK_24f7c1eb3c9d0bd6f92b95f1470" FOREIGN KEY ("createdById") REFERENCES "c0"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."works" ADD CONSTRAINT "FK_7500e37e04d3461d791ca977699" FOREIGN KEY ("updatedById") REFERENCES "c0"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."cities" ADD CONSTRAINT "FK_ded8a17cd090922d5bac8a2361f" FOREIGN KEY ("stateId") REFERENCES "c0"."states"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."states" ADD CONSTRAINT "FK_76ac7edf8f44e80dff569db7321" FOREIGN KEY ("countryId") REFERENCES "c0"."countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."timezones" ADD CONSTRAINT "FK_978bd92c90a5e7cd9bd1150b304" FOREIGN KEY ("countryId") REFERENCES "c0"."countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "c0"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."work_tags" ADD CONSTRAINT "FK_d9652285b640595c4e10185b2ab" FOREIGN KEY ("work_id") REFERENCES "c0"."works"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "c0"."work_tags" ADD CONSTRAINT "FK_55598cd484850a747685c787234" FOREIGN KEY ("tag_id") REFERENCES "c0"."tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."comments_closure" ADD CONSTRAINT "FK_89a2762362d968c2939b6fab193" FOREIGN KEY ("id_ancestor") REFERENCES "c0"."comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "c0"."comments_closure" ADD CONSTRAINT "FK_d2164211fd6ab117cfb2ab8ba96" FOREIGN KEY ("id_descendant") REFERENCES "c0"."comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }
    async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "c0"."comments_closure" DROP CONSTRAINT "FK_d2164211fd6ab117cfb2ab8ba96"`);
        await queryRunner.query(`ALTER TABLE "c0"."comments_closure" DROP CONSTRAINT "FK_89a2762362d968c2939b6fab193"`);
        await queryRunner.query(`ALTER TABLE "c0"."work_tags" DROP CONSTRAINT "FK_55598cd484850a747685c787234"`);
        await queryRunner.query(`ALTER TABLE "c0"."work_tags" DROP CONSTRAINT "FK_d9652285b640595c4e10185b2ab"`);
        await queryRunner.query(`ALTER TABLE "c0"."sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "c0"."timezones" DROP CONSTRAINT "FK_978bd92c90a5e7cd9bd1150b304"`);
        await queryRunner.query(`ALTER TABLE "c0"."states" DROP CONSTRAINT "FK_76ac7edf8f44e80dff569db7321"`);
        await queryRunner.query(`ALTER TABLE "c0"."cities" DROP CONSTRAINT "FK_ded8a17cd090922d5bac8a2361f"`);
        await queryRunner.query(`ALTER TABLE "c0"."works" DROP CONSTRAINT "FK_7500e37e04d3461d791ca977699"`);
        await queryRunner.query(`ALTER TABLE "c0"."works" DROP CONSTRAINT "FK_24f7c1eb3c9d0bd6f92b95f1470"`);
        await queryRunner.query(`ALTER TABLE "c0"."anime_details" DROP CONSTRAINT "FK_21ab4364b15e81e739b47f02c73"`);
        await queryRunner.query(`ALTER TABLE "c0"."manga_details" DROP CONSTRAINT "FK_3252e63fe8ce649770e57f35e69"`);
        await queryRunner.query(`ALTER TABLE "c0"."user_sanctions" DROP CONSTRAINT "FK_0e3a2487f5b55206963e560f9f1"`);
        await queryRunner.query(`ALTER TABLE "c0"."user_sanctions" DROP CONSTRAINT "FK_877f31988ad8db4e3c589a9e22e"`);
        await queryRunner.query(`ALTER TABLE "c0"."user_sanctions" DROP CONSTRAINT "FK_78bea893daa1ed87b5ebcd3d39d"`);
        await queryRunner.query(`ALTER TABLE "c0"."collections" DROP CONSTRAINT "FK_a14032a082010e4663568afd54b"`);
        await queryRunner.query(`ALTER TABLE "c0"."collection_entries" DROP CONSTRAINT "FK_3c196694a622fd7a594b6018b40"`);
        await queryRunner.query(`ALTER TABLE "c0"."collection_entries" DROP CONSTRAINT "FK_de1a5a32f043041ab0e7048b143"`);
        await queryRunner.query(`ALTER TABLE "c0"."ratings" DROP CONSTRAINT "FK_c85192d9b1abbd97d8962fd622b"`);
        await queryRunner.query(`ALTER TABLE "c0"."ratings" DROP CONSTRAINT "FK_4d0b0e3a4c4af854d225154ba40"`);
        await queryRunner.query(`ALTER TABLE "c0"."comments" DROP CONSTRAINT "FK_4875672591221a61ace66f2d4f9"`);
        await queryRunner.query(`ALTER TABLE "c0"."comments" DROP CONSTRAINT "FK_7e8d7c49f218ebb14314fdb3749"`);
        await queryRunner.query(`ALTER TABLE "c0"."comments" DROP CONSTRAINT "FK_0a9a028f859a61e9d1d961ec3ef"`);
        await queryRunner.query(`ALTER TABLE "c0"."tags" DROP CONSTRAINT "FK_613bccbbe697ffcb6d454c8c137"`);
        await queryRunner.query(`ALTER TABLE "c0"."tags" DROP CONSTRAINT "FK_e56de5f3dcb3c112de1e983b8e7"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_d2164211fd6ab117cfb2ab8ba9"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_89a2762362d968c2939b6fab19"`);
        await queryRunner.query(`DROP TABLE "c0"."comments_closure"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_55598cd484850a747685c78723"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_d9652285b640595c4e10185b2a"`);
        await queryRunner.query(`DROP TABLE "c0"."work_tags"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_57de40bc620f456c7311aa3a1e"`);
        await queryRunner.query(`DROP TABLE "c0"."sessions"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_c7ec626ba5f8d4aa87ebb8d113"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_b6248bf632ed7b73d6e96a2621"`);
        await queryRunner.query(`DROP TABLE "c0"."timezones"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_fa1376321185575cf2226b1491"`);
        await queryRunner.query(`DROP TABLE "c0"."countries"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_fe52f02449eaf27be2b2cb7acd"`);
        await queryRunner.query(`DROP TABLE "c0"."states"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_a0ae8d83b7d32359578c486e7f"`);
        await queryRunner.query(`DROP TABLE "c0"."cities"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_6c7a194ef8142e025933a24e0a"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_9f26e97e48cf2da0c1390bf089"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_2d85186e28e27d51cce3aec295"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_e8cdc8010caab38b2c5f139639"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_108358e19103e130c8f64405b1"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_3f1e6c57e950277bedba0323d0"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_8273d23f58ae6e8b03e35a6d53"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_dc7b60e91e76fae97b67a165a8"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_770b186e9db00e82890afef0aa"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_4efbf189b941c4cd29e278f87d"`);
        await queryRunner.query(`DROP TABLE "c0"."works"`);
        await queryRunner.query(`DROP TYPE "c0"."works_moderationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "c0"."works_publicationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "c0"."works_visibilitystatus_enum"`);
        await queryRunner.query(`DROP TYPE "c0"."works_type_enum"`);
        await queryRunner.query(`DROP TABLE "c0"."anime_details"`);
        await queryRunner.query(`DROP TABLE "c0"."manga_details"`);
        await queryRunner.query(`DROP TABLE "c0"."users"`);
        await queryRunner.query(`DROP TYPE "c0"."users_preferredlanguage_enum"`);
        await queryRunner.query(`DROP TYPE "c0"."users_subscriptiontier_enum"`);
        await queryRunner.query(`DROP TYPE "c0"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "c0"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_0e3a2487f5b55206963e560f9f"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_877f31988ad8db4e3c589a9e22"`);
        await queryRunner.query(`DROP TABLE "c0"."user_sanctions"`);
        await queryRunner.query(`DROP TYPE "c0"."user_sanctions_reason_enum"`);
        await queryRunner.query(`DROP TYPE "c0"."user_sanctions_type_enum"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_a14032a082010e4663568afd54"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_ed225078e8bf65b448b69105b4"`);
        await queryRunner.query(`DROP TABLE "c0"."collections"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_fdc119b50c517c0e9955531100"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_616ce4cf6593257b481160f85d"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_3c196694a622fd7a594b6018b4"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_de1a5a32f043041ab0e7048b14"`);
        await queryRunner.query(`DROP TABLE "c0"."collection_entries"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_3e4b080bb7591bb8ec918a3c64"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_c85192d9b1abbd97d8962fd622"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_4d0b0e3a4c4af854d225154ba4"`);
        await queryRunner.query(`DROP TABLE "c0"."ratings"`);
        await queryRunner.query(`DROP TABLE "c0"."comments"`);
        await queryRunner.query(`DROP INDEX "c0"."IDX_d90243459a697eadb8ad56e909"`);
        await queryRunner.query(`DROP TABLE "c0"."tags"`);
        await queryRunner.query(`DROP TYPE "c0"."tags_type_enum"`);
    }
}